name: nda_calculator
description: Night Duty Allowance Calculator

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  pdf: ^3.10.1
  printing: ^5.11.0

flutter:
  uses-material-design: true
  
